name: Build and deploy ASP.Net Core app to Azure Web App - ProjectResumeViewerApi

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Publish
        run: dotnet publish -c Release -o ./myapp

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./myapp
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./myapp   # <— ensure this matches the deploy ‘package’ path

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F01407272DFE4260813A22A743C47FA2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4DA2B8F4A0D04AF3BAEB94BC2157A002 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_580158BF669D454C8B1B3A5C953199F2 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ProjectResumeViewerApi
          # omit slot-name for Production, or use 'production'
          package: ./myapp
